---

- hosts: host1
  become: yes
  name: Installing apache2 on host1
  tasks:
    - name: Install apache2
      apt: name=apache2 state=latest

- hosts: host2
  become: yes
  name: Installing nginx on host2
  tasks:
    - name: installing nginx
      apt: name=nginx state=latest
